// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: internal/types/transaction.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_NormalTransaction           TransactionType = 0
	TransactionType_VerificationTransaction     TransactionType = 1
	TransactionType_ResourceTransaction         TransactionType = 2
	TransactionType_NodeRegistrationTransaction TransactionType = 3
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "NormalTransaction",
		1: "VerificationTransaction",
		2: "ResourceTransaction",
		3: "NodeRegistrationTransaction",
	}
	TransactionType_value = map[string]int32{
		"NormalTransaction":           0,
		"VerificationTransaction":     1,
		"ResourceTransaction":         2,
		"NodeRegistrationTransaction": 3,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_types_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_internal_types_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_internal_types_transaction_proto_rawDescGZIP(), []int{0}
}

type VerificationTransactionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attestation string `protobuf:"bytes,1,opt,name=attestation,proto3" json:"attestation,omitempty"`
	Cid         string `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Datasource  string `protobuf:"bytes,3,opt,name=datasource,proto3" json:"datasource,omitempty"`
	Timestamp   int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *VerificationTransactionData) Reset() {
	*x = VerificationTransactionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_types_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationTransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationTransactionData) ProtoMessage() {}

func (x *VerificationTransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationTransactionData.ProtoReflect.Descriptor instead.
func (*VerificationTransactionData) Descriptor() ([]byte, []int) {
	return file_internal_types_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationTransactionData) GetAttestation() string {
	if x != nil {
		return x.Attestation
	}
	return ""
}

func (x *VerificationTransactionData) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *VerificationTransactionData) GetDatasource() string {
	if x != nil {
		return x.Datasource
	}
	return ""
}

func (x *VerificationTransactionData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ResourceTransactionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalResources    float64 `protobuf:"fixed64,1,opt,name=totalResources,proto3" json:"totalResources,omitempty"`
	RewardedResources float64 `protobuf:"fixed64,2,opt,name=rewardedResources,proto3" json:"rewardedResources,omitempty"`
}

func (x *ResourceTransactionData) Reset() {
	*x = ResourceTransactionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_types_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceTransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTransactionData) ProtoMessage() {}

func (x *ResourceTransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTransactionData.ProtoReflect.Descriptor instead.
func (*ResourceTransactionData) Descriptor() ([]byte, []int) {
	return file_internal_types_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceTransactionData) GetTotalResources() float64 {
	if x != nil {
		return x.TotalResources
	}
	return 0
}

func (x *ResourceTransactionData) GetRewardedResources() float64 {
	if x != nil {
		return x.RewardedResources
	}
	return 0
}

type NormalTransactionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionAmount float64 `protobuf:"fixed64,1,opt,name=transactionAmount,proto3" json:"transactionAmount,omitempty"`
	SentTo            string  `protobuf:"bytes,2,opt,name=sentTo,proto3" json:"sentTo,omitempty"`
}

func (x *NormalTransactionData) Reset() {
	*x = NormalTransactionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_types_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalTransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalTransactionData) ProtoMessage() {}

func (x *NormalTransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalTransactionData.ProtoReflect.Descriptor instead.
func (*NormalTransactionData) Descriptor() ([]byte, []int) {
	return file_internal_types_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *NormalTransactionData) GetTransactionAmount() float64 {
	if x != nil {
		return x.TransactionAmount
	}
	return 0
}

func (x *NormalTransactionData) GetSentTo() string {
	if x != nil {
		return x.SentTo
	}
	return ""
}

// Node Registration Transaction Data
type NodeRegistrationTransactionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeAddress     string `protobuf:"bytes,1,opt,name=nodeAddress,proto3" json:"nodeAddress,omitempty"`
	NodeAttestation string `protobuf:"bytes,2,opt,name=nodeAttestation,proto3" json:"nodeAttestation,omitempty"`
	NodeSignature   string `protobuf:"bytes,3,opt,name=nodeSignature,proto3" json:"nodeSignature,omitempty"`
}

func (x *NodeRegistrationTransactionData) Reset() {
	*x = NodeRegistrationTransactionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_types_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeRegistrationTransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistrationTransactionData) ProtoMessage() {}

func (x *NodeRegistrationTransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistrationTransactionData.ProtoReflect.Descriptor instead.
func (*NodeRegistrationTransactionData) Descriptor() ([]byte, []int) {
	return file_internal_types_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *NodeRegistrationTransactionData) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *NodeRegistrationTransactionData) GetNodeAttestation() string {
	if x != nil {
		return x.NodeAttestation
	}
	return ""
}

func (x *NodeRegistrationTransactionData) GetNodeSignature() string {
	if x != nil {
		return x.NodeSignature
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner     string          `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Signature string          `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Type      TransactionType `protobuf:"varint,3,opt,name=type,proto3,enum=TransactionType" json:"type,omitempty"`
	// Types that are assignable to Data:
	//	*Transaction_VerificationData
	//	*Transaction_ResourceData
	//	*Transaction_NormalData
	//	*Transaction_NodeRegistrationData
	Data isTransaction_Data `protobuf_oneof:"data"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_types_transaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_transaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_internal_types_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *Transaction) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Transaction) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_NormalTransaction
}

func (m *Transaction) GetData() isTransaction_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Transaction) GetVerificationData() *VerificationTransactionData {
	if x, ok := x.GetData().(*Transaction_VerificationData); ok {
		return x.VerificationData
	}
	return nil
}

func (x *Transaction) GetResourceData() *ResourceTransactionData {
	if x, ok := x.GetData().(*Transaction_ResourceData); ok {
		return x.ResourceData
	}
	return nil
}

func (x *Transaction) GetNormalData() *NormalTransactionData {
	if x, ok := x.GetData().(*Transaction_NormalData); ok {
		return x.NormalData
	}
	return nil
}

func (x *Transaction) GetNodeRegistrationData() *NodeRegistrationTransactionData {
	if x, ok := x.GetData().(*Transaction_NodeRegistrationData); ok {
		return x.NodeRegistrationData
	}
	return nil
}

type isTransaction_Data interface {
	isTransaction_Data()
}

type Transaction_VerificationData struct {
	VerificationData *VerificationTransactionData `protobuf:"bytes,4,opt,name=verificationData,proto3,oneof"`
}

type Transaction_ResourceData struct {
	ResourceData *ResourceTransactionData `protobuf:"bytes,5,opt,name=resourceData,proto3,oneof"`
}

type Transaction_NormalData struct {
	NormalData *NormalTransactionData `protobuf:"bytes,6,opt,name=normalData,proto3,oneof"`
}

type Transaction_NodeRegistrationData struct {
	NodeRegistrationData *NodeRegistrationTransactionData `protobuf:"bytes,7,opt,name=nodeRegistrationData,proto3,oneof"`
}

func (*Transaction_VerificationData) isTransaction_Data() {}

func (*Transaction_ResourceData) isTransaction_Data() {}

func (*Transaction_NormalData) isTransaction_Data() {}

func (*Transaction_NodeRegistrationData) isTransaction_Data() {}

var File_internal_types_transaction_proto protoreflect.FileDescriptor

var file_internal_types_transaction_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x1b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x6f, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x26, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x11, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x5d, 0x0a, 0x15, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c,
	0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x74, 0x54, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x1f, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e,
	0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x6f,
	0x64, 0x65, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x6f, 0x64,
	0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x8d, 0x03, 0x0a, 0x0b, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x24,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x4a, 0x0a, 0x10, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x10,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x3e, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x38, 0x0a, 0x0a, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0a,
	0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x56, 0x0a, 0x14, 0x6e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x14, 0x6e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x7f, 0x0a, 0x0f, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a,
	0x11, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10,
	0x01, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x12, 0x1f, 0x0a, 0x1b, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x03, 0x42, 0x1e, 0x5a, 0x1c, 0x6f,
	0x70, 0x65, 0x6e, 0x6d, 0x65, 0x73, 0x68, 0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_types_transaction_proto_rawDescOnce sync.Once
	file_internal_types_transaction_proto_rawDescData = file_internal_types_transaction_proto_rawDesc
)

func file_internal_types_transaction_proto_rawDescGZIP() []byte {
	file_internal_types_transaction_proto_rawDescOnce.Do(func() {
		file_internal_types_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_types_transaction_proto_rawDescData)
	})
	return file_internal_types_transaction_proto_rawDescData
}

var file_internal_types_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_types_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_types_transaction_proto_goTypes = []interface{}{
	(TransactionType)(0),                    // 0: TransactionType
	(*VerificationTransactionData)(nil),     // 1: VerificationTransactionData
	(*ResourceTransactionData)(nil),         // 2: ResourceTransactionData
	(*NormalTransactionData)(nil),           // 3: NormalTransactionData
	(*NodeRegistrationTransactionData)(nil), // 4: NodeRegistrationTransactionData
	(*Transaction)(nil),                     // 5: Transaction
}
var file_internal_types_transaction_proto_depIdxs = []int32{
	0, // 0: Transaction.type:type_name -> TransactionType
	1, // 1: Transaction.verificationData:type_name -> VerificationTransactionData
	2, // 2: Transaction.resourceData:type_name -> ResourceTransactionData
	3, // 3: Transaction.normalData:type_name -> NormalTransactionData
	4, // 4: Transaction.nodeRegistrationData:type_name -> NodeRegistrationTransactionData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_types_transaction_proto_init() }
func file_internal_types_transaction_proto_init() {
	if File_internal_types_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_types_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationTransactionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_types_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceTransactionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_types_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NormalTransactionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_types_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeRegistrationTransactionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_types_transaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_types_transaction_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Transaction_VerificationData)(nil),
		(*Transaction_ResourceData)(nil),
		(*Transaction_NormalData)(nil),
		(*Transaction_NodeRegistrationData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_types_transaction_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_types_transaction_proto_goTypes,
		DependencyIndexes: file_internal_types_transaction_proto_depIdxs,
		EnumInfos:         file_internal_types_transaction_proto_enumTypes,
		MessageInfos:      file_internal_types_transaction_proto_msgTypes,
	}.Build()
	File_internal_types_transaction_proto = out.File
	file_internal_types_transaction_proto_rawDesc = nil
	file_internal_types_transaction_proto_goTypes = nil
	file_internal_types_transaction_proto_depIdxs = nil
}
